import { useState, useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Button } from "@/components/ui/button";
import { CopyPlus, X, Rocket, Terminal, Box, Eye, Check } from "lucide-react";

interface WizardModalProps {
    onClose: () => void;
    onRefresh: () => void;
}

const TEMPLATES = [
    {
        id: "appimage",
        name: "AppImage Wrapper",
        description: "Best for standalone binary distributions",
        icon: <Box className="w-8 h-8 text-emerald-400" />,
        generate: (name: string, p: string) => `[Desktop Entry]
Name=${name}
Exec=${p} %U
Terminal=false
Type=Application
Icon=application-x-executable
Comment=Wrapper generated by Tool Meister
Categories=Utility;
`
    },
    {
        id: "electron",
        name: "Web / Electron App",
        description: "Optimized for web-based tools",
        icon: <Rocket className="w-8 h-8 text-blue-400" />,
        generate: (name: string, p: string) => `[Desktop Entry]
Name=${name}
Exec=${p} --no-sandbox %U
Terminal=false
Type=Application
Icon=web-browser
Comment=Web Application Wrapper
Categories=Network;WebBrowser;
`
    },
    {
        id: "cli",
        name: "CLI Launcher",
        description: "Runs command in a terminal window",
        icon: <Terminal className="w-8 h-8 text-zinc-400" />,
        generate: (name: string, p: string) => `[Desktop Entry]
Name=${name}
Exec=${p}
Terminal=true
Type=Application
Icon=utilities-terminal
Categories=System;TerminalEmulator;
`
    }
];

export function WizardModal({ onClose, onRefresh }: WizardModalProps) {
    const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
    const [appName, setAppName] = useState("My New App");
    const [execPath, setExecPath] = useState("/usr/bin/echo");
    const [appsDir, setAppsDir] = useState<string>("");
    const [loading, setLoading] = useState(false);
    const [msg, setMsg] = useState("");

    useEffect(() => {
        invoke<string>("get_user_applications_dir")
            .then(setAppsDir)
            .catch(e => setMsg(`Error detecting apps directory: ${e}`));

        // Lock body scroll
        document.body.style.overflow = 'hidden';
        return () => {
            document.body.style.overflow = 'unset';
        };
    }, []);

    const currentTemplate = TEMPLATES.find(t => t.id === selectedTemplate);
    const blueprint = currentTemplate ? currentTemplate.generate(appName, execPath) : "";

    const handleCreate = async () => {
        if (!selectedTemplate || !appsDir) return;
        
        setLoading(true);
        try {
            const safeName = appName.toLowerCase().replace(/[^a-z0-9]/g, '-');
            const finalPath = `${appsDir}/${safeName}.desktop`;
            
            await invoke("git_snapshot", { message: `Auto snapshot before generating ${safeName}.desktop` });
            await invoke("save_desktop_file", { path: finalPath, content: blueprint });
            
            setMsg("Application entry created successfully!");
            setTimeout(() => {
                onRefresh();
                onClose();
            }, 1200);
        } catch (e) {
            setMsg(`Creation failed: ${e}`);
        }
        setLoading(false);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-in fade-in duration-300">
            <div className="bg-zinc-950 border border-zinc-800 rounded-2xl shadow-2xl w-full max-w-4xl overflow-hidden flex flex-col h-[80vh] animate-in zoom-in-95 duration-300">
                <div className="flex justify-between items-center p-6 bg-zinc-900/50 backdrop-blur-xl border-b border-zinc-800">
                    <div className="flex items-center gap-4">
                        <div className="p-3 bg-indigo-500/10 rounded-xl border border-indigo-500/20">
                            <CopyPlus className="w-6 h-6 text-indigo-400" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold text-zinc-100 tracking-tight">Template Wizard</h2>
                            <p className="text-sm text-zinc-500">Generate standardized XDG desktop entries</p>
                        </div>
                    </div>
                    <Button variant="ghost" size="icon" onClick={onClose} className="text-zinc-500 hover:text-white transition-colors rounded-full h-10 w-10">
                        <X className="w-6 h-6" />
                    </Button>
                </div>

                <div className="p-8 flex flex-col gap-8 overflow-y-auto">
                    {msg && (
                        <div className="p-4 bg-indigo-900/20 text-indigo-300 border border-indigo-500/30 rounded-xl animate-in slide-in-from-top-2">
                            {msg}
                        </div>
                    )}
                    
                    {!selectedTemplate ? (
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                            {TEMPLATES.map(t => (
                                <button 
                                    key={t.id} 
                                    onClick={() => setSelectedTemplate(t.id)}
                                    className="flex flex-col items-center justify-center p-8 rounded-2xl border-2 border-zinc-900 bg-zinc-900/50 hover:bg-zinc-900 hover:border-indigo-500/50 transition-all group"
                                >
                                    <div className="mb-4 transform group-hover:scale-110 transition-transform duration-300">
                                        {t.icon}
                                    </div>
                                    <span className="font-bold text-zinc-100 mb-1">{t.name}</span>
                                    <span className="text-xs text-zinc-500 text-center">{t.description}</span>
                                </button>
                            ))}
                        </div>
                    ) : (
                        <div className="flex flex-col gap-6 animate-in fade-in slide-in-from-bottom-4">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div className="space-y-4">
                                    <div className="flex flex-col gap-2">
                                        <label className="text-sm font-semibold text-zinc-400 uppercase tracking-widest px-1">App Name</label>
                                        <input 
                                            className="p-4 bg-zinc-900/80 border border-zinc-800 rounded-xl text-zinc-100 focus:ring-2 focus:ring-indigo-500/50 outline-none transition-all"
                                            value={appName}
                                            onChange={e => setAppName(e.target.value)}
                                            placeholder="e.g. My Nextjs App"
                                        />
                                    </div>
                                    <div className="flex flex-col gap-2">
                                        <label className="text-sm font-semibold text-zinc-400 uppercase tracking-widest px-1">Executable Path</label>
                                        <input 
                                            className="p-4 bg-zinc-900/80 border border-zinc-800 rounded-xl text-zinc-100 focus:ring-2 focus:ring-indigo-500/50 outline-none font-mono text-sm transition-all"
                                            value={execPath}
                                            onChange={e => setExecPath(e.target.value)}
                                            placeholder="/home/gt-dev/bin/myapp.AppImage"
                                        />
                                    </div>
                                </div>
                                <div className="bg-zinc-900/30 border border-zinc-800 rounded-2xl p-6 flex flex-col">
                                    <div className="flex justify-between items-center mb-4">
                                        <span className="text-xs font-bold text-zinc-500 uppercase flex items-center gap-2">
                                            <Eye className="w-3 h-3" /> Live Blueprint
                                        </span>
                                        <Button variant="ghost" size="sm" onClick={() => setSelectedTemplate(null)} className="h-7 text-xs text-indigo-400 hover:text-indigo-300">Change Type</Button>
                                    </div>
                                    <pre className="text-xs font-mono text-indigo-300/80 h-25 overflow-y-auto bg-black/20 p-4 rounded-lg">
                                        {blueprint}
                                    </pre>
                                    <div className="mt-4 pt-4 border-t border-zinc-800/50">
                                        <p className="text-[10px] text-zinc-500 font-mono">Will be saved to:</p>
                                        <p className="text-[10px] text-indigo-400/60 font-mono truncate">{appsDir}/{appName.toLowerCase().replace(/[^a-z0-9]/g, '-')}.desktop</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                <div className="p-6 bg-zinc-900 border-t border-zinc-800 flex justify-end gap-3">
                    <Button variant="ghost" onClick={onClose} className="text-zinc-400 hover:text-zinc-200">Cancel</Button>
                    <Button 
                        onClick={handleCreate} 
                        disabled={!selectedTemplate || loading} 
                        className="bg-indigo-600 hover:bg-indigo-700 text-white shadow-xl shadow-indigo-500/10 h-10 px-8 rounded-xl font-bold transition-all disabled:opacity-50 active:scale-95"
                    >
                        {loading ? "Generating..." : (
                            <span className="flex items-center gap-2">
                                <Check className="w-4 h-4" /> Create Entry
                            </span>
                        )}
                    </Button>
                </div>
            </div>
        </div>
    );
}
